gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  
paginate: 6
permalink: /:title/

authors:
  alejandro:
    name: Alejandro Perez
    image: /assets/authors/alejandro.jpg
    bio: Food scientist, Sommelier y Homebrewer
         Egresado de la Universidad de Guadalajara e interesado en fermentar lo que sea que encuentre, soy un 침o침o que disfruta de aprender y compartir con los dem치s mientras probamos algun nuevo alimento. En mi tiempo libre me gusta informarme sobre historia y antropologia, adem치s de practicar tai chi chuan por mi cuenta.
         Adoro viajar para conocer la forma en la que se alimentan las personas y de donde provienen esos alimentos. Mi comida favorita es el cochito horneado.
  ivan:
    name: Ivan
    image:
    bio: Hola, soy Ivan
  diego:
    name: Diego
    image:
    bio:
  brenda:
    name: Brenda Flores
    image:
    bio:
  leo:
    name: Leonardi Perez
    image:
    bio: